# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-29 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvariant',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Order'),
        ),
    ]
